
import javax.swing.JOptionPane;
import mode.User;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Precision
 */
public class LogInPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogInPanel
     */
    public LogInPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        nguoidung = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        matkhau = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login System");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        Password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Password.setText("User ID");
        jPanel2.add(Password);

        nguoidung.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nguoidungFocusLost(evt);
            }
        });
        nguoidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nguoidungActionPerformed(evt);
            }
        });
        jPanel2.add(nguoidung);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jPanel2.add(matkhau);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jButton1.setText("Resert");
        jPanel1.add(jButton1);

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void nguoidungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nguoidungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nguoidungActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String uid=nguoidung.getText();
        String pw=matkhau.getText();
        User s =User.login(uid, pw);
        if(s==null)JOptionPane.showMessageDialog(this, "LogIn Failed!");
        else JOptionPane.showMessageDialog(this, "Welcome User "+s.getFullName());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nguoidungFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nguoidungFocusLost
        String uid = nguoidung.getText();
        if(uid.length()!=5||uid.charAt(0)!='U'){
            JOptionPane.showMessageDialog(this, "Invalid userID!!!");
            nguoidung.setText("");
            nguoidung.requestFocus();
        }
    }//GEN-LAST:event_nguoidungFocusLost
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField matkhau;
    private javax.swing.JTextField nguoidung;
    // End of variables declaration//GEN-END:variables
}
